### ISSUE TITLE
PHP Fatal error:  Call to undefined method PHPUnit_Util_Type::export() in Extensions\Constraint\ArrayHasKeyValuePair.php on line 50

### ISSUE THREAD

**Issue by Jodes81** [etsy/phpunit-extensions#15]
I installed the library as follows with composer:

    "etsy/phpunit-extensions": "@stable"

But when I try using the `PHPUnit_Extensions_Constraint_ArrayHasKeyValuePair` constraint, I get the following error:

    PHP Fatal error:  Call to undefined method PHPUnit_Util_Type::export() in [...]Extensions\Constraint\ArrayHasKeyValuePair.php on line 50

**Comment by psaintlaurent** [comment]
Taken care of in 7cb1529
